---
- name: Remove dir and file of apache install to prevent failure of bindfs mount
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/www/html/index.html
    - /var/www/html

- shell: apache2 -v
  register: apache_version

- name: disable default vhost
  become: yes
  command: a2dissite 000-default.conf
  args:
    removes: /etc/apache2/sites-enabled/000-default.conf
  notify: restart apache
