---
- include: install.yml
  when: apache.install and apache_bds.install
  tags:
    - apache
    - apache_bds

- name: Include create vhosts tasks
  import_tasks: create_vhosts_tasks.yml
  when: apache.install and apache_bds.install and vagrant_local.vm.aliases|length == apache_bds.additionalvhosts_docroots|length
  tags:
    - apache
    - apache_bds
