---
- name: Download elastic search in version 2.3.3
  get_url:
    dest: "{{ elasticsearch.repo.deb_destination }}"
    url: "{{ elasticsearch.repo.deb_source }}"
    checksum: "{{ elasticsearch.repo.deb_checksum }}"

- name: Install elasticsearch
  become: yes
  shell: "dpkg -i /tmp/elasticsearch_2_3_3.deb"

- name: Set elasticsearch configuration
  template: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
  become: yes

- name: Download decompound plugin for elastic search
  become: yes
  shell: "/usr/share/elasticsearch/bin/./plugin install http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-analysis-decompound/2.3.3.0/elasticsearch-analysis-decompound-2.3.3.0-plugin.zip"

- name: restart elasticsearch
  become: yes
  service: name=elasticsearch enabled=yes state=restarted
