---
- name: Add ppa Repository
  become: yes
  apt_repository: repo=ppa:ondrej/php

- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install php5
  become: yes
  apt: pkg=php5.6 state=latest

- name: Install PHP Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items: "{{ php.packages }}"
  when: php.packages is defined
  notify:
    - restart apache

- include: configure.yml
- include: pecl.yml
- include: phpbrew.yml
