---
# check whether cli php.ini for given version exists
- stat: path=/etc/php/{{ php.version }}/cli/php.ini
  register: phpcli

# check whether yml exists of distribution specific tasks for exact version of distribution and php
- stat: path="php{{ php.version }}-cli-{{ ansible_distribution|lower }}{{ ansible_distribution_version }}.yml"
  register: distribution_specific_php_cli_tasks

# include distribution specific tasks for exact version of distribution and php
- include: "php{{ php.version }}-cli-{{ ansible_distribution|lower }}{{ ansible_distribution_version }}.yml"
  when: phpcli is defined and phpcli.stat.exists and distribution_specific_php_cli_tasks is defined and distribution_specific_php_cli_tasks.stat.exists
