---
# check whether cli php.ini for given version exists
- stat: path=/etc/php/{{ php.version }}/cli/php.ini
  register: phpcli

# include distribution specific install for exact version of distribution and php
- include: "php{{ php.version }}-cli-{{ ansible_distribution|lower }}{{ ansible_distribution_version }}.yml"
  when: phpcli is defined and phpcli.stat.exists
