---
- name: Create logfile for php cli when not exists and set attributes in both cases
  become: yes
  file:
    path: "{{ php_bds.ubuntu1604_php56cli_logfile }}"
    state: touch
    owner: root
    group: vagrant
    mode: "g+w"
  when: php_bds is defined and php_bds.ubuntu1604_php56cli_logfile is defined

- name: Set logfile in cli php.ini
  become: yes
  lineinfile: dest=/etc/php/{{ php.version }}/cli/php.ini
              regexp=';?error_log = php_errors.log'
              line="error_log = {{ php_bds.ubuntu1604_php56cli_logfile }}"
  when: php_bds is defined and php_bds.ubuntu1604_php56cli_logfile is defined
