#!/bin/bash

WANTED_VERSION=$1;

if [[ ${WANTED_VERSION} =~ ^[0-9]\.[0-9]*\.[0-9]*$ ]]; then
    # If full PHP version is specified, use it.
    FOUND_VERSION=$WANTED_VERSION
else
    # Check if there is wanted PHP version installed and take latest available patch
    FOUND_VERSION=`phpbrew list | grep php-$WANTED_VERSION | sed -E "s/.*([0-9]+\.[0-9]+\.[0-9]+)/\\1/g" | head -1`
    if [[ -z $FOUND_VERSION ]]; then
        # Get latest available PHP version for building.
        FOUND_VERSION=`phpbrew known --old | grep "\s$WANTED_VERSION" | sed -E "s/.*\:\s+([0-9]+\.[0-9]+\.[0-9]+).*/\\1/g"`
    fi
fi

echo ${FOUND_VERSION}