#!/bin/bash

WANTED_VERSION=$1;


if [[ ${WANTED_VERSION} =~ ^[0-9]\.[0-9]*\.[0-9]*$ ]]; then
    FOUND_VERSION=$WANTED_VERSION
else
    FOUND_VERSION=`phpbrew list | grep php-$WANTED_VERSION | sed -E "s/.*([0-9]+\.[0-9]+\.[0-9]+)/\\1/g" | head -1`
    if [[ -z $FOUND_VERSION ]]; then
        FOUND_VERSION=`phpbrew known --old | grep "\s$WANTED_VERSION" | sed -E "s/.*\:\s+([0-9]+\.[0-9]+\.[0-9]+).*/\\1/g"`
    fi
fi

echo ${FOUND_VERSION}